server:
  port: 23421
  undertow:
    threads:
      # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
      io: 4
      # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
      worker: 20
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true

knife4j:
  enable: true
  openapi:
    title: SpringBoot单体脚手架接口文档
    description: "**SpringBoot**单体脚手架**接口文档**"
    email: qingshanking@vip.qq.com
    concat: xiaose
    url: http://localhost:23421/doc.html
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      test1:
        group-name: 测试模块
        api-rule: package
        api-rule-resources:
          - com.yanqingshan.admin.module.test